#@ load("@ytt:overlay", "overlay")
#! iot-agent-json.yaml

#! Add the iot-agent service
#@overlay/match by=overlay.subset({"services": {}})
#@overlay/match-child-defaults missing_ok=True
---
services:
  iot-agent:
    image: fiware/iotagent-json
    hostname: iot-agent
    container_name: fiware-iot-agent
    depends_on:
      - mongo
    expose:
      - "4041"
      - "7896"
    ports:
      - "4041:4041"
      - "7896:7896"
    environment:
      - "IOTA_CB_HOST=orion"
      - "IOTA_CB_PORT=1026"
      - "IOTA_NORTH_PORT=4041"
      - "IOTA_REGISTRY_TYPE=mongodb"
      - "IOTA_MONGO_HOST=mongo"
      - "IOTA_MONGO_PORT=27017"
      - "IOTA_MONGO_DB=iotagent-json"
      - "IOTA_HTTP_PORT=7896"
      - "IOTA_PROVIDER_URL=http://iot-agent:4041"

#! Modify orion to depend on iot-agent
#@overlay/match by=overlay.subset({"services": {"orion": {}}})
---
services:
  orion:
    #@overlay/match-child-defaults missing_ok=True
    depends_on:
      #@overlay/append
      - iot-agent
